# =============================================================================
# Module: test_agent.py
# Location: tests/test_agent.py
#
# Purpose
# -------
# This module contains unit tests for the Agent class.
#
# The objective of these tests is to verify that the Agent fulfills its
# responsibility: receiving a user question, delegating the request to an LLM
# dependency, and returning the generated response.
#
# Responsibilities
# ----------------
# - Validate Agent behavior independently.
# - Replace external dependencies with deterministic fake objects.
# - Ensure tests remain isolated from real Language Models, APIs, and networks.
# =============================================================================


from ai_agent_system.agent import Agent


class FakeLLM:
    """
    A simple fake implementation of a Language Model.

    This class replaces the real LLM dependency during unit testing.

    The purpose is not to simulate intelligence, but to provide predictable
    behavior so that the Agent can be tested independently.

    Characteristics:
    - No external API calls.
    - No network dependency.
    - Deterministic output.
    - Fast execution.
    """

    def invoke(self, prompt: str) -> str:
        """
        Simulate an LLM response.

        Parameters
        ----------
        prompt : str
            The user's question.

        Returns
        -------
        str
            A fixed response used for testing.
        """

        return "This is a fake response."


def test_agent_returns_llm_response() -> None:
    """
    Verify that the Agent returns the response generated by its LLM dependency.

    This test validates only the Agent responsibility.

    The LLM itself is not tested because it is replaced by FakeLLM.
    """

    # Arrange
    fake_llm = FakeLLM()
    agent = Agent(fake_llm)

    # Act
    response = agent.answer("What is artificial intelligence?")

    # Assert
    assert response == "This is a fake response."