# ============================================================================
# Module: agent.py
# Package: ai_agent_system
# Path: src/ai_agent_system/agent.py
#
# Purpose:
# Defines the Agent class, which coordinates the interaction between the user
# and a Language Model (LLM).
#
# Responsibilities:
# - Receive a user's request.
# - Delegate reasoning to the Language Model.
# - Return the generated response.
#
# The Agent does not implement reasoning itself. Instead, it collaborates
# with an object that satisfies the LLM contract defined in llm.py.
#
# More advanced capabilities such as memory, tools, planning, and autonomous
# workflows will be introduced in later phases of the project.
# ============================================================================

from ai_agent_system.llm import LLM


class Agent:
    """
    A simple educational AI Agent.

    The Agent coordinates the interaction between the user and a Language
    Model (LLM). It delegates reasoning to the LLM and returns the generated
    response.
    """

    def __init__(self, llm: LLM) -> None:
        """
        Initialize the Agent.

        Parameters
        ----------
        llm : LLM
            A Language Model that satisfies the LLM contract.
        """
        self.llm = llm

    def answer(self, question: str) -> str:
        """
        Generate an answer for the user's question.

        Parameters
        ----------
        question : str
            The user's input.

        Returns
        -------
        str
            The response generated by the Language Model.
        """
        return self.llm.invoke(question)