"""
Module: structured_output_demo.py

Location:
    examples/

Purpose:
    Demonstrate LangChain structured outputs using a simple
    Pydantic model.

Description:
    Educational example for Phase 4.2 of the AI Agent System
    roadmap.
"""

from pydantic import BaseModel, Field
from langchain_ollama import ChatOllama


class TopicSummary(BaseModel):
    """
    Structured summary generated by the language model.

    Attributes
    ----------
    topic:
        Main topic discussed.

    summary:
        Short explanation of the topic.

    difficulty:
        Difficulty level of the explanation.
    """

    topic: str = Field(description="The main topic discussed.")

    summary: str = Field(description="A short explanation of the topic.")

    difficulty: str = Field(
        description=("Difficulty level: Beginner, Intermediate, or Advanced.")
    )


chat_model = ChatOllama(
    model="qwen3:4b",
)

structured_chat_model = chat_model.with_structured_output(
    TopicSummary,
)

response = structured_chat_model.invoke("Explain what Machine Learning is.")

print("Response Type:")
print(type(response))

print()

print("Topic:")
print(response.topic)

print()

print("Summary:")
print(response.summary)

print()

print("Difficulty:")
print(response.difficulty)
